### ISSUE TITLE
How to reload/reinitialize the list after adding a node

### ISSUE THREAD

**Issue by shailesh1490** [mechanicious/domenu#10]
hi,

I added a node into database by using some other function and now I want to refresh the tree structure  to get all the new added nodes over here.

is there any method / way to do that ?
Please guide on the above.

Thanks

**Comment by mechanicious** [comment]
See if #8 helps.

**Comment by shailesh1490** [comment]
Thank you,  it is exactly what was needed. :) 
Cheers ;)
