### ISSUE TITLE
how to save the data from domenu to Db using php and Mysql

### ISSUE THREAD

**Issue by shailesh1490** [mechanicious/domenu#11]
I tried saving the data from domenu to db, I tried flattening the array also but I am losing the sort order of the list.
I want to save the data in db with the sorted order and parent child relationship

---
## id || name || parent_id || sort_order

1 || test     || 0              || 1
2 || test     || 1              || 2
3 || test     || 1              || 3
4 || test     || 2              || 4

this is the db structure.
Below is the array format I am getting from domenu: 

<pre>
Array
(
    [0] => Array
        (
            [id] => 1
            [title] => test
            [children] => Array
                (
                    [0] => Array
                        (
                            [id] => 4
                            [title] => name
                            [children] => Array
                                (
                                    [0] => Array
                                        (
                                            [id] => 6
                                            [title] => tes2
                                            [children] => Array
                                                (
                                                    [0] => Array
                                                        (
                                                            [id] => 7
                                                            [title] => test3
                                                        )

                                                    [1] => Array
                                                        (
                                                            [id] => 5
                                                            [title] => test4
                                                        )

                                                )

                                        )

                                )

                        )

                )

        )

    [1] => Array
        (
            [id] => 2
            [title] => Digital camera
        )

    [2] => Array
        (
            [id] => 41
            [title] => Javascript
        )

    [3] => Array
        (
            [id] => 42
            [title] => asdasd
        )

    [4] => Array
        (
            [id] => 43
            [title] => asdasd
        )

    [5] => Array
        (
            [id] => 44
            [title] => 12
        )

    [6] => Array
        (
            [id] => 45
            [title] => 1233
        )

)
</pre>

Thanks

**Comment by mechanicious** [comment]
The plugin conversion relies fully on `JSON`. That means that you should store the `JSON` output from `toJson()` in your database as a single `text` string. Using `parseJson()` you're able to convert `JSON` back to doMenu.

As what you're trying to accomplish isn't supported by doMenu, I can't provide you any further assistance in programming custom features. I do however, strongly recommend you to fully enjoy the features of the plugin, not to store the plugin in a static fashion as you've described  [in your previous post](https://github.com/mechanicious/domenu/issues/11#issue-124163342).
