### ISSUE TITLE
How can I get the parent element in which a particular node is dropped?

### ISSUE THREAD

**Issue by shailesh1490** [mechanicious/domenu#12]
I want to get the parent node in which we are dropping a particular node. Just to know that which is the parent node for a particular node in the tree.

Thanks

**Comment by mechanicious** [comment]
The code below will do the job. If you're using custom selectors, make sure to adjust it accordingly:

``` js
$('#domenu').domenu().onItemDrop(function(droppedItem, event) { 
 var parentItem = $(droppedItem).parents('.dd-item'); 
});
```
