### ISSUE TITLE
How can I assign the parent for the dragged node 

### ISSUE THREAD

**Issue by shailesh1490** [mechanicious/domenu#13]
Hi,

Right now the parent is assigned when we drop the dragged node to the right of the parent node, so I want to know how can I modify this code to drop the node over a parent.

if I drop a node over a parent node it should become the child of that particular node.

Thanks

**Comment by shailesh1490** [comment]
somebody please help over this ??

**Comment by mechanicious** [comment]
To achieve this you would have to rewrite the `dragMove` method within the plugin. I am willing to accept a `pull request` which adds this feature as an optional `parent snapping`.
