### ISSUE TITLE
Want to store into db along with its refrences

### ISSUE THREAD

**Issue by pradeep07us** [mechanicious/domenu#14]
I want to store all nodes into db with its parent & child reference.

**Comment by King-ZeuS** [comment]
It's simple. Store it to input and save to database. And when you need it, read from database.

```
jQuery(document).ready(function() {
       $('#domenu').domenu({
        data: '<?=$allmenu;?>'
    }).parseJson();

    $('.save-button').on('click', function(e){
        var mydata = $('#domenu').domenu().toJson('id');
        $('#your-input').val(mydata);
        $('#yourform').submit();
    });
});
```

**Comment by mechanicious** [comment]
Like @King-ZeuS has already explained, that's one of possible ways to store all nodes to your database. However, keep in mind that the [toJson method](https://github.com/mechanicious/domenu/blob/0.48.53/jquery.domenu-0.48.53.js#L1183) doesn't take any arguments.

**Comment by pradeep07us** [comment]
Thanks @King-ZeuS  & @mechanicious
