### ISSUE TITLE
Want to call onSaveEditBoxInput to save value

### ISSUE THREAD

**Issue by pradeep07us** [mechanicious/domenu#16]
Hi Can you help me to call onSaveEditBoxInput with example outside plugin file with example.

**Comment by mechanicious** [comment]
I am afraid I don't understand the issue. Please clearly state the issue and if needed please provide enough information for me to reproduce the problem.

**Comment by pradeep07us** [comment]
Hi Mechanicious... we used another way to accomplish this task. Thanks
