### ISSUE TITLE
How to reload container ?

### ISSUE THREAD

**Issue by priyankDEVD** [mechanicious/domenu#17]
I have requirement something like that ,
initially only "ACTIVE" records will display  when page load.
once page load , I have one checkbox button on click of that , i have to reload container and display "inactive" records as well.

for that i call "ajax" , and in response of that i also get all "inactive" records with "active" records, 
but how to apply it in my old container , (means only "active" records should be rewrite with "inactive" records as well).

please help me out.
Thanks in advance.

**MY CODE:**:::

$.ajax({
                            type: "POST",
                            url: "getisdeleted_records.php",
                            data: "assessmentid="+idv,
                            success:function(data){
                                valueFromPhp=data;
                                //alert(valueFromPhp);

```
                            $('#domenu-1').domenu({
                                slideAnimationDuration: 0,
                                data: valueFromPhp
                            }).parseJson();
                        }
                    });
```

**Comment by mechanicious** [comment]
You can reload your doMenu instance using `$('#domenu-1').domenu().parseJson(newData)`. The call `$('#domenu-1').domenu()` returns the `pPlugin` object which is documented by the [pPlugin API](https://github.com/mechanicious/domenu#quick-api-reference).

**Comment by priyankDEVD** [comment]
Hello @mechanicious 
Thanks you very much .
its working for me.
