### ISSUE TITLE
How to reload/reinitialize the list after adding a node ?

### ISSUE THREAD

**Issue by priyankDEVD** [mechanicious/domenu#18]
Hi @mechanicious

can you please provide code for it ?
i need help for same .

thanks in advance.

**Comment by mechanicious** [comment]
You might be looking for `$('#domenu-1).domenu().parseJson($('#domenu-1).domenu().toJson())`.

**Comment by mechanicious** [comment]
You might be looking for:

``` js
var json = $('#domenu-1').domenu().toJson(); 
$('#domenu-1 .dd-item').remove(); 
$('#domenu-1').domenu().parseJson(json);
```

The `$('#domenu-1 .dd-item').remove()` will remove nodes from the DOM "silently" without triggering the `onItemRemoved` event.

**Comment by priyankDEVD** [comment]
Thanks @mechanicious 
This is what exactly i want .
its working.

Thank you very much once again.
