### ISSUE TITLE
How do you get the added values of a node only 

### ISSUE THREAD

**Issue by ElijahGM** [mechanicious/domenu#19]
I would like to get only the added attributes of a node on after endEdit event how is this possible

**Comment by mechanicious** [comment]
You might want to use the `item` argument inside of your callback function:

``` js
$('#domenu-1').domenu().onItemEndEdit(function(item) { item })
```

The `item` is the edited element.

**Comment by ElijahGM** [comment]
Thank you for a quick reply

**Comment by ElijahGM** [comment]
I am trying to access the id,url, parent, children of the added node, but am not successfull

 .onItemEndEdit(function(item) {
                    var data = item.serialize();
                    $('#page-9').prepend(JSON.stringify(data));  
                    console.log('event: onItemEndEdit', 'arguments:', arguments, 'context:', this);
                })

**Comment by mechanicious** [comment]
This should serialize the edited inputs and prepend JSON-stringified `data` to `#page-9` element.

``` js
$('#domenu-1').domenu().onSaveEditBoxInput(function(inputs) {
  var data = inputs.serialize();
  $('#page-9').prepend(JSON.stringify(data));
});
```

**Comment by ElijahGM** [comment]
That worked, thanks, but i cannot get the parent ID

**Comment by mechanicious** [comment]
To get the parent `id` you might want to try `$('#domenu-1').domenu().onItemEndEdit(function(item) { console.log(item.parent().attr('id')) })`. However, by default `nodes` do not have an `id` attribute.

**Comment by ElijahGM** [comment]
**Let me explain what i exactly need to achieve**

I want to implement a system that has a hierarchical order, so when

**A new Item is added**
  I get the values of the new Item node and save it to db, the data to be fetched include **parent id, and all inputs values**

**On Drag and Drop**
 This includes reorganizing the nodes, data that i need is parent id of the ordered node and position it is on the hierarchy

**Comment by ElijahGM** [comment]
The id that i want to fetch is the one from data settings

data: '[{"id":1,"title":"Home","att-title":"home","url":"<?=base_url()?>""},{"id":10,"title":"News","att-title":"","url":"http://demo.com"}]'
