### ISSUE TITLE
How to get list and store it to database ?

### ISSUE THREAD

**Issue by darkcyber** [mechanicious/domenu#2]
Hello @mechanicious ,

So far i create `nav_menu` table, which contain `id, object_id, parent_id, order`, `object_id` is represent page, post, or category in my case, `parent_id` will be `0` for nav menu in root level, so if nav menu not in root level it must have `parent_id` and `order`, order is start from 1.

So how i can get list and store it to database, maybe you can help me with easy example.

Thanks

**Comment by mechanicious** [comment]
You're overthinking it, just store the JSON parsed doMenu, which you can get with `$(your_domenu_selector).domenu().toJson()`, in your database (either using a form or AJAX). If you're using PHP and want to render it to a custom menu HTML use [`decode_json()`](http://php.net/manual/en/function.json-decode.php) and loop through it ...etc

To render back doMenu from the JSON string you've stored in your database use `$(your_domenu_selector).domenu().parseJson(JSON_string)`.

Reference to [Quick API Reference](https://github.com/mechanicious/domenu#quick-api-reference) for overview of methods you can use with doMenu.

**Comment by darkcyber** [comment]
@mechanicious 
Hi bro thanks for response, but my idea is store default navigation menu in `nav_menu_table` then if admin change navigation menu, it will return json then decode it and update the table because i will use it to render for front end view, like this.

id | object_id | title | parrent_id | order 
-- | ------------ | ---- |---------- | ----------
1 | 3 | Home | 0 | 1
2 | 4 | About | 0 | 2
3 | 2 | Contact Us | 4 | 1
4 | 6 | Phone | 2 | 1
5 | 8 | Android | 6 | 1

`object_id` value is from `posts` table which related to `nav_menu` table, so it will like this trees view

```
Home
About
--- Contact Us
     ------ Phone
              ---- Android
```

I create some pseudo code to show menu for backend view from database source like this.

```
$menu = [];
loop 5 times
loop 1

        X = get parrent
        $menu_item['id'] = id1
        $menu_item['title'] = title1
        $child1 = []
        $menu_item['children'] = $child1
        if parent_id 0
            push to $menu
        else
            push to $childX
loop 2
        X = get parrent
        menu_item['id'] = id2
        menu_item['title'] = title2
        $child2 = []
        menu_item['children'] = $child2
        if parent 0
            push to $menu
        else
            push to $childX
and so on
```

now how to save new item and new order if admin make some changes ? i think click save button, get json lists and parse it to php and store it to database.

But i confuse how i can do nested loop to decode json, especially the children section, then it will be PHP array and save it to database ?

i dont know if my algorithm is bad idea to create navigation menu, or maybe you can give me nice algorithm to create navigation menu since this is my first time create navigation menu.

**Comment by mechanicious** [comment]
`func flatten m`

**Comment by mechanicious** [comment]
I'll get back to you once I get on my PC. Can't quite answer from my phone.

**Comment by mechanicious** [comment]
See the pseudocode below on how to flatten the JSON data.

``` dart
array func flattenMenu string json
    var array itemsCollection
          array parsedJson is jsonDecode json

    func flattenItem array item, item childOf
        // When the item has children...
        if item.hasKey children      
        // ... flatten each child; and push the current item to the menuCollection after removing children
        then foreach child of children flattenItem child, item 
        and item.removeKey children
               item['childOf'] set childOf['id']
                   itemsCollection.push item

        // When the item has no children simply push is to the itemsCollection
        else itemsCollection.push item
    end flattenItem

    foreach item of parsedJson flattenItem item

    // Give back the itemsCollection
    return itemsCollection
end flattenMenu
```
