### ISSUE TITLE
How to store doMenu to the database using AJAX and reinitialize it?

### ISSUE THREAD

**Issue by Axel29** [mechanicious/domenu#20]
Hi,

It might be a stupid question, but the goal of this plugin isn't to create / edit menus? If so, I'm trying to use the event listeners like onItemAdded, onItemRemoved etc. but the function parameters never seem to actually get the item data like it's ID, it's parent etc.

The question is: how can we access these data? I want to perform an AJAX call at every modification to save it into database but the problem is I can never access the item's ID...

Thank you for your help.

**Comment by mechanicious** [comment]
You might want to store the JSON output of `toJson` to the database and rebuild the doMenu instance using the stored JSON and the `parseJson` method. You might also want to refer to #14.

``` js
var doMenuJson = $('#domenu-instance').domenu().toJson();
$('#domenu-instance').domenu().onSaveEditBoxInput(function() {
  // Storing doMenuJson to the database on the onSaveEditBoxInput event using AJAX...
  jQuery.post('http://someBackend/store/domenu', doMenuJson, function(responseData) {});

$(document).ready(function() {
  // Fetching the doMenu instance from the database
  jQuery.get('http://someBackend/read/domenu', function(doMenuJson) {
    // Reinitializing the doMenu instance using the received data
    $('#domenu-instance').domenu().parseJson(doMenuJson);
  }
});
```

**Comment by Axel29** [comment]
Wow thanks for such a quick answer! 
I guess the parseJson(doMenuJson) should be in every event listener like onSaveEditBoxInput() ? If so this is my code

``` javascript
var doMenuJson = $('#doMenu').domenu({
    data: domenuData
})
.parseJson()
.onSaveEditBoxInput(function(inputs) {
    console.log('event: onSaveEditBoxInput', 'arguments:', arguments, 'context:', this);
    console.log($('#doMenu').domenu().parseJson(doMenuJson));
})
```

But this gives me an error in the console:

> Uncaught
>  SyntaxError: Unexpected token o
>     at Object.parse (native)
>     at Object.eval (eval at evaluate (unknown source), <anonymous>:1:6)
>     at Object.InjectedScript._evaluateOn (<anonymous>:875:55)
>     at Object.InjectedScript._evaluateAndWrap (<anonymous>:808:34)
>     at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:933:21)
>     at Object.Plugin.deserialize > (http://mywebsite.localhost.com/app/templates/admin/js/jquery.domenu-0.48.53.js:733:7)
>     at Object.PublicPlugin.parseJson > (http://mywebsite.localhost.com/app/templates/admin/js/jquery.domenu-0.48.53.js:1180:20)
>     at Object.<anonymous> > (http://mywebsite.localhost.com/app/templates/admin/js/scripts.js:175:38)
>     at http://mywebsite.localhost.com/app/templates/admin/js/jquery.domenu-0.48.53.js:439:9
>     at Array.forEach (native)

**Comment by mechanicious** [comment]
Your code doesn't comply with the doMenu API, please refer to the documentation on the main page of the project.

**Comment by Axel29** [comment]
Hi,

Sorry about that, took that example from the index.html file ^^"

I tried your code but this gives me an infinite loop on the event :S

EDIT: Finally managed to do it thanks to this post : https://github.com/mechanicious/domenu/issues/14
