### ISSUE TITLE
Alternate edit modes and assigning custom class to items

### ISSUE THREAD

**Issue by s0By** [mechanicious/domenu#21]
I'm trying to achieve several things. First of all, thank you on the great work you did on this solution.

So my questions are: 
1. Currently when you enter an edit mode of the title, it remains in it until you press a button or press enter on the keyboard, I wanted it to end also when I click outside of placeholder.
<img width="1085" alt="screen shot 2016-02-26 at 12 38 48" src="https://cloud.githubusercontent.com/assets/6382468/13350187/4729f256-dc87-11e5-9941-ea2174987ab1.png">
1. How can I assign classes to an item? For example there's no-drag class, I know how it works but how can I assign it? Also I created my own class for a item, so it would be different colour and not-draggable and wanted to use it in my solution.
   <img width="1084" alt="screen shot 2016-02-26 at 12 45 47" src="https://cloud.githubusercontent.com/assets/6382468/13350189/474dabc4-dc87-11e5-954f-7d9ff2bdbae4.png">
2. I wanted to have 2 edit types. As you can see I have 2 columns, first (left one) is the old fashioned way, to add category through typing and selecting and when you click add it would appear in the nestable. So first edit would be the current one, as you meant it to be, by clicking on the title and dragging the item around, and the second edit would be to click on the edit button and it would transfer the data back to the left column so I could edit from there. What would be the easiest way to add an extra button so it would transfer an item data to the form?
   <img width="1063" alt="screen shot 2016-02-26 at 12 42 31" src="https://cloud.githubusercontent.com/assets/6382468/13350188/474a7152-dc87-11e5-97d5-15c2a02eb822.png">

**Comment by mechanicious** [comment]
> 1. Currently when you enter an edit mode of the title, it remains in it until you press a button or press enter on the keyboard, I wanted it to end also when I click outside of placeholder.

``` js
var offEditBoxClickEndsEdit = function(e) {
  if(! $(e.target).parents('.dd-edit-box:visible').length) $('.dd-edit-box:visible .end-edit').click();
};
$('#domenu-1').domenu().onItemEndEdit(function() { $(document).off('mouseup', offEditBoxClickEndsEdit); })
$('#domenu-1').domenu().onItemStartEdit(function() { $(document).on('mouseup', offEditBoxClickEndsEdit); })
```

> 1. How can I assign classes to an item? For example there's no-drag class, I know how it works but how can I assign it? Also I created my own class for a item, so it would be different colour and not-draggable and wanted to use it in my solution.

You can request a feature for doMenu to automatically infer such class from your HTML such that an item blueprint with `class="dd-item-blueprint my-custom-class"` will render as `class="dd-item my-custom-class"` upon a `parseJson` call. I am open to hear about any ideas to include in the next versions of doMenu.

> 1. I wanted to have 2 edit types. As you can see I have 2 columns, first (left one) is the old fashioned way, to add category through typing and selecting and when you click add it would appear in the nestable. So first edit would be the current one, as you meant it to be, by clicking on the title and dragging the item around, and the second edit would be to click on the edit button and it would transfer the data back to the left column so I could edit from there. What would be the easiest way to add an extra button so it would transfer an item data to the form?

A way to do it is to add a custom button to your HTML-template in the `.button-container` container. Then, using appropriate events, make sure the functionality of the button gets initialized. The next version of doMenu will feature an additional event listener which will enable you to create custom initialization code for each `.dd-item` providing your callback with contextual information about each item you're currently processing.

As I have already mentioned earlier, please let me know what functionality would you like to see in the next versions. Functionality requests should carry an issue tag "enhancement".

**Comment by s0By** [comment]
So currently editBtnHTML:            '<button data-action="edit"     type="button">edit</button>' is just a dummy code, as you don't have any reference to it in a code? I guess I can add it through the blueprint and add a listener to it to transfer the data. 

Okey, let's assume I'm able to get all the data out with json and edit the classes and other stuff using jquery. Question is how can I add stuff inside the domenu? As I don't see any proper documentation and looking on the functions I only see how to get stuff out. At the moment of initialization elements get inside through 'data'. What do I need to do after initialization? 

Or a better way would be to wait for a new version? How far away is it by the way?

**Comment by mechanicious** [comment]
What you're are looking for is the developer's API. As doMenu is a simple piece of code developers are assumed to understand the code from analyzing it themselves, occasionally there are commented blocks of code to help you out. Any other simplification of analyzing the code like a developer's API you must provide yourself with.

**Comment by mechanicious** [comment]
The module which manages the "old" way of editing should establish a bridge to doMenu. Using JSON could be an appropriate way to carry the messages between your module and doMenu.
