### ISSUE TITLE
Loading data using get_file_contents throws Uncaught SyntaxError: Unexpected token o

### ISSUE THREAD

**Issue by midi9x** [mechanicious/domenu#23]
Hello,
Can I using data form url json?
I use file_get_contents, but there is error 'Uncaught SyntaxError: Unexpected token o'
Please help me.
Thanks

**Comment by mechanicious** [comment]
Make sure your JSON data is a string. `JSON.parse({"hi":"hi"})` will throw `Uncaught SyntaxError: Unexpected token o`. Doing it this way: `JSON.parse('{"hi":"hi"}')` won't throw an error.

**Comment by midi9x** [comment]
![image](https://cloud.githubusercontent.com/assets/12813165/13656599/d5dda458-e69a-11e5-9196-4c46926e11b6.png)
it's my code. please help me

**Comment by midi9x** [comment]
although the data is loaded
![image](https://cloud.githubusercontent.com/assets/12813165/13656671/6d7aa98c-e69b-11e5-82c2-c16a6734b1d7.png)

**Comment by mechanicious** [comment]
![image](https://cloud.githubusercontent.com/assets/8450319/13662164/ca179522-e698-11e5-9f32-12a3f7e43a2d.png)

**Comment by midi9x** [comment]
Hello, I fixed it with JSON.stringify() :D
