### ISSUE TITLE
Additional functionality

### ISSUE THREAD

**Issue by s0By** [mechanicious/domenu#24]
Additional methods and events would be nice to have in this plugin. 
For the question I asked about in #22 I can't find a parent while I'm in `dragStart`. I need a method, something like `onItemMove` that would kick in the `dragMove` function. I can't utilize `placeClass` to find my parent (I mean technically I can) but it's no use, since I don't have a method with which I could check where it's being move on the go, onItemDrag kicks in when I start dragging and onItemDrop when it's ended, meaning `placeClass` doesn't exist anymore. Since parent is being set while you do the `dragMove` I guess the necessity of `getParent` method is clear as well (even the `setParent` would be great for the flexibility in the future). Due to the lack of this method I can't imitate the placeholder getting red (showing restriction of dragging) and bouncing back to original place (as in nestedSortable) which would be really nice and intuitive.

It would be great to have some output varieties, like toArray, toHierarchy etc (idea from nestedSortable, looks handy).

I though nestable dragging (from the original solution) was done well enough, why did you decide to tune it?

Any approx. date when new release is coming?

**Comment by mechanicious** [comment]
> Additional methods and events would be nice to have in this plugin. 
> For the question I asked about in #22 I can't find a parent while I'm in dragStart. I need a method, something like onItemMove that would kick in the dragMove function. I can't utilize placeClass to find my parent (I mean technically I can) but it's no use, since I don't have a method with which I could check where it's being move on the go, onItemDrag kicks in when I start dragging and onItemDrop when it's ended, meaning placeClass doesn't exist anymore. Since parent is being set while you do the dragMove I guess the necessity of getParent method is clear as well (even the setParent would be great for the flexibility in the future). Due to the lack of this method I can't imitate the placeholder getting red (showing restriction of dragging) and bouncing back to original place (as in nestedSortable) which would be really nice and intuitive.

Please use the `onItemMaxDepth(callback)` event listener.

> It would be great to have some output varieties, like toArray, toHierarchy etc (idea from nestedSortable, looks handy).

I recognize this request, stay updated.

> I though nestable dragging (from the original solution) was done well enough, why did you decide to tune it?

The dragging is being tuned and will improve in the next release.

> Any approx. date when new release is coming?

Next release (1.0) is scheduled approximately in the first week of may 2016. This release will establish the first stable API.
