### ISSUE TITLE
prevent post inside form

### ISSUE THREAD

**Issue by rodrigoporcionato** [mechanicious/domenu#25]
Hi there,

I use you code inside a form. When a click in any button in nestable, occurs a submit.

How to fix it?

My sample:

```
             `<form id="EditDocument" name="EditDocument"  class="form-horizontal p-sm">
<div class="form-horizontal">
    <div class="validation-message" style="display:none;">
        <ul></ul>
    </div>
    @if (Model != null && Model.Any())
    {
        for (int i = 0; i < Model.OrderBy(x => x.Ordem).ToList().Count(); i++)
        {
            @Html.HiddenFor(m => m[i].CDCId)
            @Html.HiddenFor(m => m[i].Token)
            @Html.HiddenFor(m => m[i].Id)
            @Html.HiddenFor(m => m[i].Titulo)
            <div class="form-group">
                <h5>@Html.DisplayFor(m => m[i].Titulo)</h5>
                @Html.TextAreaFor(m => m[i].Descricao, new { @class = "editors" })
                @Html.ValidationMessageFor(m => m[i].Descricao, "", new { @class = "text-danger" })
            </div>
        }
    }
    <div class="dd" id="domenu-0">
        <button class="dd-new-item">+</button>
        <li class="dd-item-blueprint">
            <button class="collapse" data-action="collapse" type="button" style="display: none;">–</button>
            <button class="expand" data-action="expand" type="button" style="display: none;">+</button>
            <div class="dd-handle dd3-handle">Drag</div>
            <div class="dd3-content">
                <span class="item-name">[item_name]</span>
                <div class="dd-button-container">
                    <button class="item-add">+</button>
                    <button class="item-remove" data-confirm-class="item-remove-confirm">&times;</button>
                </div>
                <div class="dd-edit-box" style="display: none;">
                    <input type="text" name="title" autocomplete="off" placeholder="Item"
                           data-placeholder="Any nice idea for the title?"
                           data-default-value="doMenu List Item. {?numeric.increment}">
                    <i class="end-edit">save</i>
                </div>
            </div>
        </li>
        <ol class="dd-list"></ol>
    </div>



    <div class="col-md-12"></div>
    <div class="form-group">
        <div class="col-md-12">
            <input type="button" value="Alterar Documento" class="btn btn-primary btn-lg btnEditDocument" data-loading-text="Aguarde..." />
        </div>
    </div>
</div>
```

</form>`

I use in my form with button that send the json and save in db.

**Comment by mechanicious** [comment]
Prevent the default behaviour on `button` clicks contained within `.dd`:

``` js
$('.dd button').click(function(e){ e.preventDefault(); })
```

**Comment by Preeti2** [comment]
Hi,
I am facing the same issue but suggested solution work only for main plus button resides at the top.
my form gets always submitted on edit, of add item, remove an item.

I am using jquery.domenu-0.100.77.js version.

I am working in PHP file.
In one file second PHP file is loaded, this second file has this ddMenu.
Here is my 
First.php
<?php include APPPATH . '/front-modules/views/top.php'; ?>  
<link rel="stylesheet" href="<?php echo $this->config->item('css_url'); ?>jquery.fancybox.css"/>
<script type="text/javascript" src="<?php echo $this->config->item('js_url'); ?>bootstrap-filestyle.min.js"></script>


<link rel="stylesheet" href="<?php echo $this->config->item('js_url'); ?>jstree/style.css"/>

<link rel="stylesheet" href="<?php echo $this->config->item('css_url'); ?>jquery.domenu-0.100.77.css"/>
<link rel="stylesheet" href="<?php echo $this->config->item('css_url'); ?>presentation-style.css"/>

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/styles/github.min.css"/>

<div class="content-wrapper">
    
    <section class="content-header">
        <h1><?php
            if ($mode == 'add') {
                echo 'Add Book Image';
            } else {
                echo 'Edit Book Image';
            }
            ?>
        </h1>
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->config->item("site_url") . 'books' ?>"><i class="fa  fa-user"></i>Book List</a></li>            
            <li class="active"><?php
                if ($mode == 'add') {
                    echo 'Add Book Image';
                } else {
                    echo 'Edit Book Image';
                }
                ?>
            </li>
        </ol>
    </section>
    <section class="content">
        <div class="wizard-container box box-default">
            <div class="card wizard-card" data-color="azure" id="wizard">                
                <form method="POST" name="publicationImage" id="publicationImage" action="<?php echo $this->config->item("site_url") . 'book/book_image_add_action' ?>" role="form" enctype="multipart/form-data">
                    <div class="wizard-navigation">
                        <div class="progress-with-circle">
                            <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="1" aria-valuemax="3" style="width: 21%;"></div>
                        </div>
                        <ul class='step-head'>
                            <li data-stepno='1'>
                                <a href="#step1" data-toggle="tab">
                                    <div class="icon-circle"><span class="ti-list">1</span></div>
                                    <div class="heading">Define the Image</div>
                                </a>
                            </li>
                            <li data-stepno='2'>
                                <a href="#step2" data-toggle="tab">
                                    <div class="icon-circle"><span class="ti-list">2</span></div>
                                    <div class="heading">Define the Hierarchy</div>
                                </a>
                            </li>
                            <li data-stepno='3'>
                                <a href="#step3" data-toggle="tab">
                                    <div class="icon-circle"><span class="ti-list">3</span></div>
                                    <div class="heading">Define Contact</div>
                                </a>
                            </li>
                            <li data-stepno='4'>
                                <a href="#step4" data-toggle="tab">
                                    <div class="icon-circle"><span class="ti-list last-step">3</span></div>
                                    <div class="heading">Save the Contact</div>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane" id="step1">
                            <div class="row">
                                <div class="row">                                
                                    <input type="hidden" id="imgvlidate" value="0"/>                            
                                    <input type="hidden" name="bookimage" id="bookimage" value="<?php echo $image; ?>">
                                    <input type="hidden" name="book" id="book" value="<?php echo $book; ?>">
                                    <input type="hidden" name="mode" id="mode" value="<?php echo $mode; ?>">
                                    <input type="hidden" id="mode1" value="1">
                                    <div class="col-md-12">
                                        <div class="col-md-6">            
                                            <?php if (!isset($all[0]['iBookImageId'])) { ?>
                                                <div class="form-group">
                                                    <label for="exampleInputPassword1">Image <span style="color: red;">*</span></label>
                                                    <input class="form-control" type="file" id="p_image" name="p_image" accept="image/jpeg, image/jpg" data-buttonText="Find file" required>
                                                </div>
                                            <?php } else { ?>
                                                <div class="form-group">                                        
                                                    <label class="" for="columns-text">Image : </label><br>                                        
                                                    <div class="input-group gallery" style="width: 100%">
                                                        <?php
                                                        $img_url = '';
                                                        if ($all[0]['vOriginalImage'] != '') {
                                                            $img = 'book/' . $all[0]['iBookId'] . '/' . $all[0]['vOriginalImage'];
                                                            $img_path = $this->config->item('upload_path') . $img;
                                                            if (file_exists($img_path)) {
                                                                $img_url = $this->config->item('upload_url') . $img;
                                                            }
                                                        }
                                                        ?>
                                                        <input type="file" id="p_image" name="p_image" style="<?php echo ($img_url != '') ? 'display:none' : ''; ?>" accept=".jpg,.jpeg">
                                                        <button type="button" id="cancel" class="btn btn-danger" style="display:none; margin-top: 0.3em;"><i class="fa fa-times"></i></button>
                                                        <?php if ($img_url != '') { ?>
                                                            <div class="col-md-6" id="vProfileImg">
                                                                <input type="hidden" id="hiddenval" value="1">
                                                                <a class="thumb no-ajaxify" href="javascript:void(0);" data-gallery="gallery">
                                                                    <img src="<?php echo $this->config->item('upload_url') . 'book/' . $all[0]['iBookId'] . '/' . $all[0]['vOriginalImage']; ?>"  alt="photo" class="img-responsive" style="height: 150px"></a>
                                                            </div>
                                                        <?php } ?>
                                                    </div>                                       
                                                </div>
                                            <?php } ?>                                
                                            <div class="form-group">
                                                <label>Scanning Distance</label>
                                                <select class="form-control" name="distance" id="distance" style="width: 100%;">
                                                    <option value="72">2.3 to 7 inches</option>
                                                    <option value="36">4.2 to 13 inches</option>
                                                    <option value="24">6 to 18 inches</option>
                                                    <option value="18">8 to 23 inches</option>
                                                    <option value="14">10 to 28 inches</option>                                        
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label>Status</label>
                                                <select class="form-control" name="status" id="status" style="width: 100%;">
                                                    <?php
                                                    foreach ($imagestatus as $imagestatusk => $imagestatusv) {
                                                        echo '<option value="' . $imagestatusv . '" ' . (isset($all[0]['eStatus']) && $imagestatusv == $all[0]['eStatus'] ? 'Selected' : '') . ' >' . $imagestatusv . '</option>';
                                                    }
                                                    ?>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label>Hierarchy Type <span style="color: red;">*</span></label>
                                                <select class="form-control" name="hyrar_type" id="hyrar_type" style="width: 100%;" required onchange="resetStep(this.value);" required>
                                                    <option value="tops">TopScorer</option>
                                                    <option value="custom">Customized</option>                                                        
                                                </select>
                                            </div>
                                        </div>   
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Validity <span style="color: red;">*</span></label>
                                                <div class="input-group date">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-calendar"></i>
                                                    </div>
                                                    <input type="text" class="form-control pull-right" id="validity" name='validity' required='required' value="<?php echo isset($book_validity) ? $book_validity : ''; ?>">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Remarks for Validity <span style="color: red;">*</span></label>
                                                <input type="text" class="form-control" id='remark' name='remark' required='required' minlength="5" maxlength="50">
                                            </div>
                                            <div class="form-group">
                                                <label>Page Number</label>
                                                <input type="number" min='1' max="5000" class="form-control" id='pagenumber' name='pagenumber'>
                                            </div>
                                            <div class="form-group">
                                                <label>Page Title</label>
                                                <input type="text" minlength="3" maxlength="50" class="form-control" id='pagetitle' name='pagetitle'>
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="step2">
                            <div class="ct" id="ct" style='dislay: none;'>                                
                                <?php $this->load->view('ct_heirarchy'); ?>                                
                            </div>
                            <div class="ts cbxTree" id='ts' style='dislay: none;'>
                                <?php
                                if (isset($tsHKey)):
                                    echo 'data found';
                                else:
                                    echo 'No data found';
                                endif;
                                ?>
                            </div>
                        </div>
                        <div class="tab-pane" id="step3">
                            <h4>Defined Content </h4><br>
                            
                        </div>
                        <div class="tab-pane" id="step4">
                            <h4>Save Content</h4><br>
                            <div class="box-body">
                                <table id="example1" class="table table-hover table-bordered table-striped">
                                    <thead class="bg-light-blue">
                                        <tr>
                                            <th>Sr. No.</th>
                                            <th>Content Type</th>
                                            <th>Quantity</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1</td>
                                            <td>Videos</td>
                                            <td id='videocount'>0</td>
                                        </tr>

                                        <tr>
                                            <td>3</td>
                                            <td>Tests</td>
                                            <td id='testcount'>0</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="wizard-footer">
                        <div class="pull-right" id='stpbutton'>
                            <input type='button' class='btn btn-next btn-fill btn-primary btn-wd step-nav' id='step-nav' name='next' value='Next' />
                            <input type='submit' class='btn btn-finish btn-fill btn-primary btn-wd' name='finish' value='Finish' />
                        </div>
                        <div class="pull-left">
                            <input type='button' class='btn btn-previous btn-default btn-wd' name='previous' value='Previous' />
                        </div>
                        <div class="clearfix"></div>
                    </div>                        
                </form>
            </div>
        </div> 
    </section>
</div>
    </div>
</div>

        </div>
    </div>
</div>



<script type="text/javascript" src="<?php echo $this->config->item('js_url'); ?>custom/book_image.js"></script>


<script type="text/javascript" src="<?php echo $this->config->item('js_url'); ?>jstree/jstree.min.js"></script>

<script type="text/javascript" src="<?php echo $this->config->item('js_url'); ?>jquery.domenu-0.100.77.js"></script>    

<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/highlight.min.js"></script>




Here is my second file ie. ct_heirarchy.php
<p>Create Customized Hierarchy</p>
<div class="dd" id="domenu-1">
        <button id="domenu-add-item-btn" class="dd-new-item">+</button>        
        <li class="dd-item-blueprint">            
            <button class="collapse" data-action="collapse" type="button" style="display: none;">–</button>
            <button class="expand" data-action="expand" type="button" style="display: none;">+</button>
            <div class="dd-handle dd3-handle">&nbsp;</div>
            <div class="dd3-content">
                <span class="item-name">[item_name]</span>                
                <div class="dd-button-container">                    
                    <button class="custom-button-example">&#x270E;</button>
                    <button class="item-add">+</button>
                    <button class="item-remove" data-confirm-class="item-remove-confirm">&times;</button>
                </div>                
                <div class="dd-edit-box" style="display: none;">                    
                    <input type="text" name="title" autocomplete="off" placeholder="Item"
                           data-placeholder="Any nice idea for the title?"
                           data-default-value="H {?numeric.increment}">
                    <i class="end-edit">save</i>
                </div>
            </div>
        </li>
        <ol class="dd-list"></ol>
    </div>
