### ISSUE TITLE
Rewrite to Babel

### ISSUE THREAD

**Issue by mechanicious** [mechanicious/domenu#26]
Hi, I've started a rewrite of doMenu to Babel which includes the following features but is not limited to:
- unit testing
- separate interfaces for Instances, Blueprints, Lists and Items
- improved code maintainability
- helpful error reporting

If you are interested in contributing to the project let me know in this issue.

**Comment by s0By** [comment]
What about the promised update in the first week of may?

**Comment by mechanicious** [comment]
@s0By Although it's delayed, it's on its way. It's being worked on in parallel with the rewrite to ES6/Babel.
