### ISSUE TITLE
after received json how to save data in database if child leave is more than 5-10 

### ISSUE THREAD

**Issue by vishal92patel** [mechanicious/domenu#27]
(1) after received json how to save data in database if child/sub-child leave is more than 5-10 ?
(2) how to get order id/sort id of menus

**Comment by mechanicious** [comment]
I am afraid I don't understand your question, please include enough information for me to reproduce the problem, since your terminology doesn't comply with terminology established for this project I recommend you to use screenshots.

**Comment by mechanicious** [comment]
I am afraid I don't understand the issue, please include enough information in your question for me to reproduce the problem.
