### ISSUE TITLE
how to find my json id

### ISSUE THREAD

**Issue by marcdakar** [mechanicious/domenu#28]
hi there,
my json data below  populate nice to domenu
{
                "id": 92,
                "parent": 87,
                "title": "Extras_sub_2",
                "aktiv": 1,
                "seo": "de/extras/extras_sub_2",
                "customSelect": 0,
                "children": [ ] .....

but how can i retrieve the id (92) when i call 
 .onItemRemoved(function(item) { console.log(item) }

thank you for help
marc

**Comment by mechanicious** [comment]
I guess you don't. What you do is convert all nodes back to JSON and overwrite your database data with it.

**Comment by marcdakar** [comment]
thats a pity, so i dont know easy which nodes to delete ... have to delete the table an build it new. By errors i get a real frontend problem ... 
=> one possibility for domenu would be not to delete the node from the json but mark them as deleted
but thank you anyway
marc

**Comment by mechanicious** [comment]
I will leave the issue open. This functionality may be added in the future, stay tuned.

**Comment by mechanicious** [comment]
Here's how you do it:
```js
.onItemRemoved(function(item) { item.data("id") }
```
