### ISSUE TITLE
onItemRemoved function

### ISSUE THREAD

**Issue by AybimYazilim** [mechanicious/domenu#29]
how can i find removed item id ?

i use this function but return always undefined.

.onItemRemoved(function(item) { console.log(item.data('id')) });

thanks

**Comment by mechanicious** [comment]
I have updated the `callback` of `onItemRemoved` to take `id` as second argument.

So, this is what you are looking for:
```js
.onItemRemoved(function(item, id) { console.log(id) });
```

**Comment by AybimYazilim** [comment]
Ok, its fixed. Thanks
