### ISSUE TITLE
When parsing JSON the selected url does not load

### ISSUE THREAD

**Issue by CallMeAreks** [mechanicious/domenu#3]
When I try to make doMeny parse the JSON string it creates the menues and children items correctly, but does not populate the previously selected url in the select.

Is this case not supported yet?

**Comment by mechanicious** [comment]
Hi, thanks for your post. I'll arrange a quick patch for this once I get home. Cheers.

**Comment by CallMeAreks** [comment]
Hi, is there any update to this issue?

**Comment by mechanicious** [comment]
I've pushed a patched version (v0.13.37) in which this issue should be solved. Please confirm whether this solves the issue.

**Comment by shakyapranin** [comment]
Similar issue as @AlejandroGC , but i am not able to populate previous value in a custom added text box.
Thanx in advance.

**Comment by mechanicious** [comment]
Hi, thank you for your message. Please consider creating a separate issue with a complete description of the problem providing enough data to replicate the possible bug which would enable me to look into it.
