### ISSUE TITLE
Select2 dropdown selection selects option text instead of option value.

### ISSUE THREAD

**Issue by faizansaiyed** [mechanicious/domenu#30]
Hi,
I've created DoMenu with custom select2 where drop-down is populated with data containing UrlLink and UrlName where I want to show UrlName in the drop-down, but when any drop-down item is selected, the doMenu JSON should pick option value, not the option text.

**Comment by faizansaiyed** [comment]
Working fine. My bad.

**Comment by mechanicious** [comment]
No problem. I am glad it's working.
