### ISSUE TITLE
your's  domenu Nestable plugin is very useful for me thank you for this stuff.

### ISSUE THREAD

**Issue by shoaibgurmani** [mechanicious/domenu#32]
but i'm facing a problem please consider my problem.
when is use this function for finding parent id 
$('#domenu-1').domenu().onItemEndEdit(function(item) 
{ console.log(item.parent().attr('id')) }))
then i received a error in consol like onItemEndEdit() is not a function .
could you please help me to find the problem 
thank you.
regard shoaib

**Comment by mechanicious** [comment]
Hey, have you resolved it? `onItemEndEdit` is defenitely a function, see the [source code](https://github.com/mechanicious/domenu/blob/master/jquery.domenu-0.100.77.js#L1579).
