### ISSUE TITLE
I dont want to allow parent be child of anothe parent

### ISSUE THREAD

**Issue by coolboy4598** [mechanicious/domenu#34]
Hello,

thanks a ton for such a wonderful plugin. I don't want to allow parent be child of another parent. But yes it should be allowed to drag as need to allow sorting.

@mechanicious please help me.

thanks

**Comment by coolboy4598** [comment]
any body please help me

**Comment by mechanicious** [comment]
@Preeti2 Githib issues are meant for project related issues and not for searching a solution to your own problem. For that try posting on Stackoverflow or something alike. Cheers.

**Comment by Preeti2** [comment]
@mechanicious

> @Preeti2 Githib issues are meant for project related issues and not for searching a solution to your own problem. For that try posting on Stackoverflow or something alike. Cheers.

It is not my post. why you taggedit to me?
