### ISSUE TITLE
D in menu FIX

### ISSUE THREAD

**Issue by InsiteFX** [mechanicious/domenu#37]
This is the line that is putting the D in your menus, just remove the Drag leave it blank.

`<div class="dd-handle dd3-handle">Drag</div>`

That's all you need to do to fix it.

**Comment by Preeti2** [comment]
Hi,

As you recently commented here, I ask you for some help, which is really a road blocker for my work.
I need some customization in this plugin, as follow
 
How to display remove button(x sign on li )only at end child level. (User should not remove item if it parent level).

I am working in a 4 step wizard, in which 2 step user set some hierarchy item as per his requirement, in 3rd step all menu display with previous selection(here user can only show his work not edit it, ie. add, edit, remove button should be disabled, how to do it.?)

Thanks in advance.

**Comment by mechanicious** [comment]
@Preeti2 Githib issues are meant for project related issues and not for searching a solution to your own problem. For that try posting on Stackoverflow or something alike. Cheers.
