### ISSUE TITLE
Duplication of item when moving a child item from a parent item and placing it into same level as the parent.

### ISSUE THREAD

**Issue by shakyapranin** [mechanicious/domenu#4]

**Comment by mechanicious** [comment]
Thank you for your message. Please consider providing enough data for me to exactly replicate the possible bug which will enable me to look into it.

Note that after removing a child item (by clicking the delete button), you're not able to place it into same level as the parent anymore since the item has already been removed.

**Comment by shakyapranin** [comment]
Glad you replied.I also have edited my issue. NOTE: I have added an extra field named "tagline"
My issue can be replicated by following the steps below:
The pic below shows the initial state of the menu and json data
![initialmenu](https://cloud.githubusercontent.com/assets/6336873/10810144/d6730a44-7e25-11e5-8bfe-6c30fe1258c7.PNG)
JSON 1:

``` json
 [{"title":"About Us","url":"http://demourl/about_us","tagline":"demo tagline","children":[{"title":"Services","url":"http://demourl/services","tagline":"asdf"}]},{"title":"Portfolio","url":"http://demorul/portfolio","tagline":"asdfa"},{"title":"Contact Us","url":"http://demourl/contact","tagline":"asdfads"}]
```

Step 1:
Move an item to create sub menu
![moveintoaparent](https://cloud.githubusercontent.com/assets/6336873/10810267/2a50b138-7e27-11e5-8617-614712262775.PNG)
JSON 2:

``` json
[{"title":"About Us","url":"http://demourl/about_us","tagline":"demo tagline change abt us","children":[{"title":"Services","url":"http://demourl/services","tagline":"asdf"}]},{"title":"Portfolio","url":"http://demourl/portfolio","tagline":"asdfa"},{"title":"Contact Us","url":"http://demourl/contact","tagline":"asdfads"}]
```

After making the above changes I stored the json record in the database.
Then again i retrieve records and my json data is the same as JSON 2. It renders fine when i pass it in `$('#domenu').domenu({data: menuData}).parseJson();`

Now the problem arises when i perform the next step

Step 3:
I moved the child back to its original position.
![backtoinitialstate](https://cloud.githubusercontent.com/assets/6336873/10810451/3ef321be-7e29-11e5-8973-d105a8b52847.PNG)

Now the json data is 
JSON 3:

``` json
[{"title":"About Us","url":"http://demourl/about_us","tagline":"demo tagline change abt us","children":[{"title":"Services","url":"http://demourl/services","tagline":"asdf"}]},{"title":"Services","url":"http://demourl/services","tagline":"asdf"},{"title":"Portfolio","url":"http://demourl/portfolio","tagline":"asdfa"},{"title":"Contact Us","url":"http://demourl/contact","tagline":"asdfads"}]
```

NOTICE how services data is still persisting as a child even after moving the element.
Now this JSON Data will yield a menu as follows on rendering.
![flaseresult](https://cloud.githubusercontent.com/assets/6336873/10810568/7137c1b0-7e2a-11e5-8823-e4269e3c97ea.PNG)

Finally:
You may also see in the first pic how the about us bears a "-" sign even if it doesn't have any children.This is most probably caused by ("children":) in the JSON 1 as i had previously created its child element and later moved/removed it.

THANK YOU AGAIN FOR THIS GREAT PLUGIN ENHANCEMENT AND HOPE TO HEAR SOON FROM YOU,CHEERS!!!

**Comment by mechanicious** [comment]
Hi thank you for your wonderful description of the problem, I was successfully able to replicate this problem and I've recognized it as a bug. I will patch this as soon as possible. Also, the ghost-child ('-' sign on empty parents) has already been solved in the next version of doMenu, which is about to get released soon.

**Comment by mechanicious** [comment]
Hi, this bug has been patched in the dev-version of the plugin. I will release the patched version to the public when I complete writing the release notes, however you can use the patched version right now if you're able to figure it out yourself how to use it (there is a working demo available and the files contain instructions in the comments). Please confirm the validity of the patch on your side, if possible.

**Comment by shakyapranin** [comment]
Hi,it's me again.I integrated the developer version of your plugin and it does not work with JSON data i have mentioned above(NOTE: IT WORKS with the JSON data from the DEVELOPER VERSION).I would like to ask why you have added an "id" field for your items, I presume you used some logic identifying unique items to solve the child duplication issue.I also tried using the code below to add the unique id:
/</ input type="hidden" name="id" data-default-value="{?numeric.increment}" />/

But the problem here is it yields a string value and your plugin expects "id" field to be numeric I suppose.

THE STATIC JSON DATA YOU PASSED IN THE DEVELOPER DEMO IS:

``` json
[
  {
    "id": 11,
    "title": "Flat Glass Preview",
    "http": "",
    "superselect": "2"
  },
  {
    "id": 10,
    "title": "News",
    "http": "",
    "superselect": "1"
  },
  {
    "id": 9,
    "title": "Categories",
    "http": "",
    "superselect": "1"
  },
  {
    "id": 6,
    "title": "Shop",
    "http": "",
    "children": [
      {
        "id": 5,
        "title": "Glass",
        "http": "",
        "superselect": "1"
      },
      {
        "title": "Other",
        "superselect": "select something..."
      }
    ],
    "superselect": "select something..."
  },
  {
    "id": 1,
    "title": "About",
    "http": "",
    "superselect": "select something..."
  }
]
```

THE JSON DATA I'm able to yield by adding the hidden input mentioned above is:

``` json
[
  {
    "title": "Item no. 3",
    "tagline": "",
    "id": "1",
    "superselect": "http://demourl/portfolio/17"
  },
  {
    "title": "Item no. 2",
    "tagline": "",
    "id": "2",
    "superselect": "http://demourl/portfolio/17",
    "children": [
      {
        "title": "Item no. 1",
        "tagline": "",
        "id": "3",
        "superselect": "http://demourl/portfolio/17"
      }
    ]
  },
  {
    "title": "Item no. 1",
    "tagline": "",
    "id": "3",
    "superselect": "http://demourl/portfolio/17"
  },
  {
    "id": "4",
    "title": "Item no. 0",
    "http": "",
    "superselect": "http://demourl/portfolio/17",
    "tagline": ""
  }
]
```

You may notice how the "id" values are string, so the child duplication problem still persists.

I really appreciate your help and I am thankful for the enhancement of custom fields I suggested.Cheers!!

**Comment by mechanicious** [comment]
Hi thank you for your reply. Note that the id property is added by default
without any explicit inputs in your blueprint. Please make sure to create a
correct blueprint template in your html markup (default
".dd-item-blueprint"). Also note that this standard id field is present in the previous versions as well.

**Comment by shakyapranin** [comment]
Thank you for your reply. I had previously used the blue print template from your demo and have also reviewed it. I noticed that ADDING NEW MENU ITEMS THROUGH "+" button WONT yield "id" property while going through the JSON.
So i edited the JSON from your developer demo as

``` json
[
  {
    "title": "Flat Glass Preview",
    "http": "",
    "superselect": "2"
  },
  {
    "title": "News",
    "http": "",
    "superselect": "1"
  },
  {
    "title": "Categories",
    "http": "",
    "superselect": "1"
  },
  {
    "title": "Shop",
    "http": "",
    "children": [
      {
        "title": "Glass",
        "http": "",
        "superselect": "1"
      },
      {
        "title": "Other",
        "superselect": "select something..."
      }
    ],
    "superselect": "select something..."
  },
  {
    "title": "About",
    "http": "",
    "superselect": "select something..."
  }
]
```

This then replicated the child duplication error.Thank you for your time.

**Comment by mechanicious** [comment]
Thank you for your reply. Please check the patch I've just pushed on the dev branch, and confirm its validity.

**Comment by shakyapranin** [comment]
Thank you !! The latest patch solved the problem for me.
