### ISSUE TITLE
Custom input field to carry additional information about menu item, doesn't retain previous value

### ISSUE THREAD

**Issue by shakyapranin** [mechanicious/domenu#5]
I have created an additional field named "tagline".
Everything is working fine, until i try to parse the previous "tagline" value as JSON into 
$('#domenu').domenu({data: menuData}).parseJson();

My JSON is:

``` json
 [{"title":"About Us","url":"http://demourl/about_us","tagline":"demo tagline change abt us","children":[]},{"title":"Services","url":"http://demourl/services","tagline":"asdf"},{"title":"Portfolio","url":"http://demourl/portfolio","tagline":"asdfa"},{"title":"Contact Us","url":"http://demourl/contact","tagline":"asdfads"}]
```

But the previous value is not retained in the Menu UI as shown:
![valuenotretained](https://cloud.githubusercontent.com/assets/6336873/10810852/4df253d4-7e2d-11e5-980c-e10db23cb58e.PNG)
I also read that you have solved an issue similar to mine for the select dropdown items.

Thank you and hope to hear soon from you.

**Comment by mechanicious** [comment]
Hi, this enhancement has been added in the dev-version of the plugin. I will release the patched version to the public when I complete writing the release notes, however you can use the patched version right now if you're able to figure it out yourself how to use it (there is a working demo available and the files contain instructions in the comments). Please confirm the validity of the patch on your side, if possible.

**Comment by shakyapranin** [comment]
Thank you this enhancement helped me a lot.
