### ISSUE TITLE
How do you recommend to completely delete plugin instance from memory? 

### ISSUE THREAD

**Issue by SebastianTroc** [mechanicious/domenu#7]
I need to remove the instance after leaving the view in a SPA.
When I'm coming back to the view and reinitialize doMenu on the new DOM element, all callbacks are fired +1 times.
Unfortunately doMenu doesn't have any API method to destroy.
Any ideas?

**Comment by mechanicious** [comment]
Please provide me enough data (browser info, plugin info, your method step-by-step and actual code snippets) to reproduce the problem. Note that every `.dd-item` has a custom `remove` method, `$('#your-domenu-instance .dd-item').remove()`. Thank you for your input.
